package raylib

import (
	rl "github.com/gen2brain/raylib-go/raylib"

	"github.com/go-glx/input/system/input/keyboard"
)

type raylibKeyCode = int32

var mapping = map[keyboard.Key]raylibKeyCode{
	keyboard.KeyF1:  rl.KeyF1,
	keyboard.KeyF2:  rl.KeyF2,
	keyboard.KeyF3:  rl.KeyF3,
	keyboard.KeyF4:  rl.KeyF4,
	keyboard.KeyF5:  rl.KeyF5,
	keyboard.KeyF6:  rl.KeyF6,
	keyboard.KeyF7:  rl.KeyF7,
	keyboard.KeyF8:  rl.KeyF8,
	keyboard.KeyF9:  rl.KeyF9,
	keyboard.KeyF10: rl.KeyF10,
	keyboard.KeyF11: rl.KeyF11,
	keyboard.KeyF12: rl.KeyF12,

	keyboard.Key0: rl.KeyZero,
	keyboard.Key1: rl.KeyOne,
	keyboard.Key2: rl.KeyTwo,
	keyboard.Key3: rl.KeyThree,
	keyboard.Key4: rl.KeyFour,
	keyboard.Key5: rl.KeyFive,
	keyboard.Key6: rl.KeySix,
	keyboard.Key7: rl.KeySeven,
	keyboard.Key8: rl.KeyEight,
	keyboard.Key9: rl.KeyNine,

	keyboard.KeyMinus:  rl.KeyMinus,
	keyboard.KeyEquals: rl.KeyEqual,

	keyboard.KeyA: rl.KeyA,
	keyboard.KeyB: rl.KeyB,
	keyboard.KeyC: rl.KeyC,
	keyboard.KeyD: rl.KeyD,
	keyboard.KeyE: rl.KeyE,
	keyboard.KeyF: rl.KeyF,
	keyboard.KeyG: rl.KeyG,
	keyboard.KeyH: rl.KeyH,
	keyboard.KeyI: rl.KeyI,
	keyboard.KeyJ: rl.KeyJ,
	keyboard.KeyK: rl.KeyK,
	keyboard.KeyL: rl.KeyL,
	keyboard.KeyM: rl.KeyM,
	keyboard.KeyN: rl.KeyN,
	keyboard.KeyO: rl.KeyO,
	keyboard.KeyP: rl.KeyP,
	keyboard.KeyQ: rl.KeyQ,
	keyboard.KeyR: rl.KeyR,
	keyboard.KeyS: rl.KeyS,
	keyboard.KeyT: rl.KeyT,
	keyboard.KeyU: rl.KeyU,
	keyboard.KeyV: rl.KeyV,
	keyboard.KeyW: rl.KeyW,
	keyboard.KeyX: rl.KeyX,
	keyboard.KeyY: rl.KeyY,
	keyboard.KeyZ: rl.KeyZ,

	keyboard.KeyRight: rl.KeyRight,
	keyboard.KeyLeft:  rl.KeyLeft,
	keyboard.KeyDown:  rl.KeyDown,
	keyboard.KeyUp:    rl.KeyUp,

	keyboard.KeyTilda:     rl.KeyGrave,
	keyboard.KeyBackspace: rl.KeyBackspace,
	keyboard.KeyTab:       rl.KeyTab,
	keyboard.KeyCapslock:  rl.KeyCapsLock,
	keyboard.KeyReturn:    rl.KeyEnter,
	keyboard.KeyEscape:    rl.KeyEscape,
	keyboard.KeySpace:     rl.KeySpace,
	keyboard.KeyLCtrl:     rl.KeyLeftControl,
	keyboard.KeyRCtrl:     rl.KeyRightControl,
	keyboard.KeyLShift:    rl.KeyLeftShift,
	keyboard.KeyRShift:    rl.KeyRightShift,
	keyboard.KeyLAlt:      rl.KeyLeftAlt,
	keyboard.KeyRAlt:      rl.KeyRightAlt,

	keyboard.KeyComma:        rl.KeyComma,
	keyboard.KeyPeriod:       rl.KeyPeriod,
	keyboard.KeySlash:        rl.KeySlash,
	keyboard.KeySemicolon:    rl.KeySemicolon,
	keyboard.KeyQuote:        rl.KeyApostrophe,
	keyboard.KeyLeftBracket:  rl.KeyLeftBracket,
	keyboard.KeyRightBracket: rl.KeyRightBracket,
	keyboard.KeyBackslash:    rl.KeyBackSlash,

	keyboard.KeyDelete:      rl.KeyDelete,
	keyboard.KeyInsert:      rl.KeyInsert,
	keyboard.KeyPrintScreen: rl.KeyPrintScreen,
	keyboard.KeyScrollLock:  rl.KeyScrollLock,
	keyboard.KeyPause:       rl.KeyPause,
	keyboard.KeyHome:        rl.KeyHome,
	keyboard.KeyEnd:         rl.KeyEnd,
	keyboard.KeyPageUp:      rl.KeyPageUp,
	keyboard.KeyPageDown:    rl.KeyPageDown,

	keyboard.KeyKpDivide:   rl.KeyKpDivide,
	keyboard.KeyKpMultiply: rl.KeyKpMultiply,
	keyboard.KeyKpMinus:    rl.KeyKpSubtract,
	keyboard.KeyKpPlus:     rl.KeyKpAdd,
	keyboard.KeyKpEnter:    rl.KeyKpEnter,
	keyboard.KeyKp1:        rl.KeyKp1,
	keyboard.KeyKp2:        rl.KeyKp2,
	keyboard.KeyKp3:        rl.KeyKp3,
	keyboard.KeyKp4:        rl.KeyKp4,
	keyboard.KeyKp5:        rl.KeyKp5,
	keyboard.KeyKp6:        rl.KeyKp6,
	keyboard.KeyKp7:        rl.KeyKp7,
	keyboard.KeyKp8:        rl.KeyKp8,
	keyboard.KeyKp9:        rl.KeyKp9,
	keyboard.KeyKp0:        rl.KeyKp0,
}
