package sdl2

import (
	"github.com/veandco/go-sdl2/sdl"

	"github.com/go-glx/input/system/input/keyboard"
)

type sdlKeyCode = sdl.Keycode

var actionMapping = map[uint8]keyboardState{
	uint8(sdl.PRESSED):  keyboardStatePressed,
	uint8(sdl.RELEASED): keyboardStateReleased,
}

var mapping = map[sdlKeyCode]keyboard.Key{
	sdl.K_F1:  keyboard.KeyF1,
	sdl.K_F2:  keyboard.KeyF2,
	sdl.K_F3:  keyboard.KeyF3,
	sdl.K_F4:  keyboard.KeyF4,
	sdl.K_F5:  keyboard.KeyF5,
	sdl.K_F6:  keyboard.KeyF6,
	sdl.K_F7:  keyboard.KeyF7,
	sdl.K_F8:  keyboard.KeyF8,
	sdl.K_F9:  keyboard.KeyF9,
	sdl.K_F10: keyboard.KeyF10,
	sdl.K_F11: keyboard.KeyF11,
	sdl.K_F12: keyboard.KeyF12,

	sdl.K_0: keyboard.Key0,
	sdl.K_1: keyboard.Key1,
	sdl.K_2: keyboard.Key2,
	sdl.K_3: keyboard.Key3,
	sdl.K_4: keyboard.Key4,
	sdl.K_5: keyboard.Key5,
	sdl.K_6: keyboard.Key6,
	sdl.K_7: keyboard.Key7,
	sdl.K_8: keyboard.Key8,
	sdl.K_9: keyboard.Key9,

	sdl.K_MINUS:  keyboard.KeyMinus,
	sdl.K_EQUALS: keyboard.KeyEquals,

	sdl.K_a: keyboard.KeyA,
	sdl.K_b: keyboard.KeyB,
	sdl.K_c: keyboard.KeyC,
	sdl.K_d: keyboard.KeyD,
	sdl.K_e: keyboard.KeyE,
	sdl.K_f: keyboard.KeyF,
	sdl.K_g: keyboard.KeyG,
	sdl.K_h: keyboard.KeyH,
	sdl.K_i: keyboard.KeyI,
	sdl.K_j: keyboard.KeyJ,
	sdl.K_k: keyboard.KeyK,
	sdl.K_l: keyboard.KeyL,
	sdl.K_m: keyboard.KeyM,
	sdl.K_n: keyboard.KeyN,
	sdl.K_o: keyboard.KeyO,
	sdl.K_p: keyboard.KeyP,
	sdl.K_q: keyboard.KeyQ,
	sdl.K_r: keyboard.KeyR,
	sdl.K_s: keyboard.KeyS,
	sdl.K_t: keyboard.KeyT,
	sdl.K_u: keyboard.KeyU,
	sdl.K_v: keyboard.KeyV,
	sdl.K_w: keyboard.KeyW,
	sdl.K_x: keyboard.KeyX,
	sdl.K_y: keyboard.KeyY,
	sdl.K_z: keyboard.KeyZ,

	sdl.K_RIGHT: keyboard.KeyRight,
	sdl.K_LEFT:  keyboard.KeyLeft,
	sdl.K_DOWN:  keyboard.KeyDown,
	sdl.K_UP:    keyboard.KeyUp,

	sdl.K_BACKQUOTE: keyboard.KeyTilda,
	sdl.K_BACKSPACE: keyboard.KeyBackspace,
	sdl.K_TAB:       keyboard.KeyTab,
	sdl.K_CAPSLOCK:  keyboard.KeyCapslock,
	sdl.K_RETURN:    keyboard.KeyReturn,
	sdl.K_ESCAPE:    keyboard.KeyEscape,
	sdl.K_SPACE:     keyboard.KeySpace,
	sdl.K_LCTRL:     keyboard.KeyLCtrl,
	sdl.K_RCTRL:     keyboard.KeyRCtrl,
	sdl.K_LSHIFT:    keyboard.KeyLShift,
	sdl.K_RSHIFT:    keyboard.KeyRShift,
	sdl.K_LALT:      keyboard.KeyLAlt,
	sdl.K_RALT:      keyboard.KeyRAlt,

	sdl.K_COMMA:        keyboard.KeyComma,
	sdl.K_PERIOD:       keyboard.KeyPeriod,
	sdl.K_SLASH:        keyboard.KeySlash,
	sdl.K_SEMICOLON:    keyboard.KeySemicolon,
	sdl.K_QUOTE:        keyboard.KeyQuote,
	sdl.K_LEFTBRACKET:  keyboard.KeyLeftBracket,
	sdl.K_RIGHTBRACKET: keyboard.KeyRightBracket,
	sdl.K_BACKSLASH:    keyboard.KeyBackslash,

	sdl.K_DELETE:      keyboard.KeyDelete,
	sdl.K_INSERT:      keyboard.KeyInsert,
	sdl.K_PRINTSCREEN: keyboard.KeyPrintScreen,
	sdl.K_SCROLLLOCK:  keyboard.KeyScrollLock,
	sdl.K_PAUSE:       keyboard.KeyPause,
	sdl.K_HOME:        keyboard.KeyHome,
	sdl.K_END:         keyboard.KeyEnd,
	sdl.K_PAGEUP:      keyboard.KeyPageUp,
	sdl.K_PAGEDOWN:    keyboard.KeyPageDown,

	sdl.K_KP_DIVIDE:   keyboard.KeyKpDivide,
	sdl.K_KP_MULTIPLY: keyboard.KeyKpMultiply,
	sdl.K_KP_MINUS:    keyboard.KeyKpMinus,
	sdl.K_KP_PLUS:     keyboard.KeyKpPlus,
	sdl.K_KP_ENTER:    keyboard.KeyKpEnter,
	sdl.K_KP_1:        keyboard.KeyKp1,
	sdl.K_KP_2:        keyboard.KeyKp2,
	sdl.K_KP_3:        keyboard.KeyKp3,
	sdl.K_KP_4:        keyboard.KeyKp4,
	sdl.K_KP_5:        keyboard.KeyKp5,
	sdl.K_KP_6:        keyboard.KeyKp6,
	sdl.K_KP_7:        keyboard.KeyKp7,
	sdl.K_KP_8:        keyboard.KeyKp8,
	sdl.K_KP_9:        keyboard.KeyKp9,
	sdl.K_KP_0:        keyboard.KeyKp0,
}
