package glfw

import (
	"github.com/go-gl/glfw/v3.3/glfw"

	"github.com/go-glx/input/system/input/keyboard"
)

type glfwKeyCode = glfw.Key

var actionMapping = map[glfw.Action]keyboardState{
	glfw.Press:   keyboardStatePressed,
	glfw.Release: keyboardStateReleased,
	glfw.Repeat:  keyboardStateDown,
}

var mapping = map[glfwKeyCode]keyboard.Key{
	glfw.KeyF1:  keyboard.KeyF1,
	glfw.KeyF2:  keyboard.KeyF2,
	glfw.KeyF3:  keyboard.KeyF3,
	glfw.KeyF4:  keyboard.KeyF4,
	glfw.KeyF5:  keyboard.KeyF5,
	glfw.KeyF6:  keyboard.KeyF6,
	glfw.KeyF7:  keyboard.KeyF7,
	glfw.KeyF8:  keyboard.KeyF8,
	glfw.KeyF9:  keyboard.KeyF9,
	glfw.KeyF10: keyboard.KeyF10,
	glfw.KeyF11: keyboard.KeyF11,
	glfw.KeyF12: keyboard.KeyF12,

	glfw.Key0: keyboard.Key0,
	glfw.Key1: keyboard.Key1,
	glfw.Key2: keyboard.Key2,
	glfw.Key3: keyboard.Key3,
	glfw.Key4: keyboard.Key4,
	glfw.Key5: keyboard.Key5,
	glfw.Key6: keyboard.Key6,
	glfw.Key7: keyboard.Key7,
	glfw.Key8: keyboard.Key8,
	glfw.Key9: keyboard.Key9,

	glfw.KeyMinus: keyboard.KeyMinus,
	glfw.KeyEqual: keyboard.KeyEquals,

	glfw.KeyA: keyboard.KeyA,
	glfw.KeyB: keyboard.KeyB,
	glfw.KeyC: keyboard.KeyC,
	glfw.KeyD: keyboard.KeyD,
	glfw.KeyE: keyboard.KeyE,
	glfw.KeyF: keyboard.KeyF,
	glfw.KeyG: keyboard.KeyG,
	glfw.KeyH: keyboard.KeyH,
	glfw.KeyI: keyboard.KeyI,
	glfw.KeyJ: keyboard.KeyJ,
	glfw.KeyK: keyboard.KeyK,
	glfw.KeyL: keyboard.KeyL,
	glfw.KeyM: keyboard.KeyM,
	glfw.KeyN: keyboard.KeyN,
	glfw.KeyO: keyboard.KeyO,
	glfw.KeyP: keyboard.KeyP,
	glfw.KeyQ: keyboard.KeyQ,
	glfw.KeyR: keyboard.KeyR,
	glfw.KeyS: keyboard.KeyS,
	glfw.KeyT: keyboard.KeyT,
	glfw.KeyU: keyboard.KeyU,
	glfw.KeyV: keyboard.KeyV,
	glfw.KeyW: keyboard.KeyW,
	glfw.KeyX: keyboard.KeyX,
	glfw.KeyY: keyboard.KeyY,
	glfw.KeyZ: keyboard.KeyZ,

	glfw.KeyRight: keyboard.KeyRight,
	glfw.KeyLeft:  keyboard.KeyLeft,
	glfw.KeyDown:  keyboard.KeyDown,
	glfw.KeyUp:    keyboard.KeyUp,

	glfw.KeyGraveAccent:  keyboard.KeyTilda,
	glfw.KeyBackspace:    keyboard.KeyBackspace,
	glfw.KeyTab:          keyboard.KeyTab,
	glfw.KeyCapsLock:     keyboard.KeyCapslock,
	glfw.KeyEnter:        keyboard.KeyReturn,
	glfw.KeyEscape:       keyboard.KeyEscape,
	glfw.KeySpace:        keyboard.KeySpace,
	glfw.KeyLeftControl:  keyboard.KeyLCtrl,
	glfw.KeyRightControl: keyboard.KeyRCtrl,
	glfw.KeyLeftShift:    keyboard.KeyLShift,
	glfw.KeyRightShift:   keyboard.KeyRShift,
	glfw.KeyLeftAlt:      keyboard.KeyLAlt,
	glfw.KeyRightAlt:     keyboard.KeyRAlt,

	glfw.KeyComma:        keyboard.KeyComma,
	glfw.KeyPeriod:       keyboard.KeyPeriod,
	glfw.KeySlash:        keyboard.KeySlash,
	glfw.KeySemicolon:    keyboard.KeySemicolon,
	glfw.KeyApostrophe:   keyboard.KeyQuote,
	glfw.KeyLeftBracket:  keyboard.KeyLeftBracket,
	glfw.KeyRightBracket: keyboard.KeyRightBracket,
	glfw.KeyBackslash:    keyboard.KeyBackslash,

	glfw.KeyDelete:      keyboard.KeyDelete,
	glfw.KeyInsert:      keyboard.KeyInsert,
	glfw.KeyPrintScreen: keyboard.KeyPrintScreen,
	glfw.KeyScrollLock:  keyboard.KeyScrollLock,
	glfw.KeyPause:       keyboard.KeyPause,
	glfw.KeyHome:        keyboard.KeyHome,
	glfw.KeyEnd:         keyboard.KeyEnd,
	glfw.KeyPageUp:      keyboard.KeyPageUp,
	glfw.KeyPageDown:    keyboard.KeyPageDown,

	glfw.KeyKPDivide:   keyboard.KeyKpDivide,
	glfw.KeyKPMultiply: keyboard.KeyKpMultiply,
	glfw.KeyKPSubtract: keyboard.KeyKpMinus,
	glfw.KeyKPAdd:      keyboard.KeyKpPlus,
	glfw.KeyKPEnter:    keyboard.KeyKpEnter,
	glfw.KeyKP1:        keyboard.KeyKp1,
	glfw.KeyKP2:        keyboard.KeyKp2,
	glfw.KeyKP3:        keyboard.KeyKp3,
	glfw.KeyKP4:        keyboard.KeyKp4,
	glfw.KeyKP5:        keyboard.KeyKp5,
	glfw.KeyKP6:        keyboard.KeyKp6,
	glfw.KeyKP7:        keyboard.KeyKp7,
	glfw.KeyKP8:        keyboard.KeyKp8,
	glfw.KeyKP9:        keyboard.KeyKp9,
	glfw.KeyKP0:        keyboard.KeyKp0,
}
